[project]
name = "teamtask-server"
version = "0.1.0"
requires-python = ">=3.12.10"
dependencies = [
    "fastapi>=0.126.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.38.0",
]
